const productos = [
  {
    id: 1,
    nombre: "Sofá Patagonia",
    descripcion: "Sofá amplio de líneas contemporáneas, pensado para el living de uso diario.",
    descripcionCompleta: "El Sofá Patagonia es la pieza central de cualquier living moderno. Con su estructura de madera maciza de eucaliptus y tapizado en tela de alta resistencia, combina elegancia y durabilidad. Sus líneas limpias y contemporáneas se adaptan a cualquier estilo decorativo, mientras que sus cojines de espuma de alta densidad garantizan el máximo confort para largas horas de descanso.",
    categoria: "Living",
    precio: 185000,
    material: "Madera de eucaliptus, tapizado en tela",
    dimensiones: "220 cm × 90 cm × 80 cm",
    imagen: "Kit de imágenes/Sofá Patagonia.png",
    destacado: true,
  },
  {
    id: 2,
    nombre: "Sillón Copacabana",
    descripcion: "Sillón individual con tapizado cálido y estructura de madera artesanal.",
    descripcionCompleta: "El Sillón Copacabana es una pieza de artesanía pura. Fabricado a mano en nuestro taller con madera de roble seleccionada, su tapizado en cuero sintético de alta calidad le otorga un aspecto premium y un tacto suave. Perfecto para crear un rincón de lectura o complementar cualquier living con carácter y distinción.",
    categoria: "Living",
    precio: 92000,
    material: "Madera de roble, tapizado en cuero sintético",
    dimensiones: "80 cm × 85 cm × 95 cm",
    imagen: "Kit de imágenes/Sillón Copacabana.png",
    destacado: true,
  },
  {
    id: 3,
    nombre: "Butaca Mendoza",
    descripcion: "Butaca de lectura con respaldo envolvente y presencia de taller.",
    descripcionCompleta: "La Butaca Mendoza fue diseñada para quienes valoran el confort en cada detalle. Su respaldo envolvente abraza naturalmente la postura del cuerpo, ideal para largas sesiones de lectura. Fabricada en madera de pino macizo con acabado natural, su estructura robusta garantiza décadas de uso conservando su belleza original.",
    categoria: "Living",
    precio: 68000,
    material: "Madera de pino macizo, tapizado en tela",
    dimensiones: "70 cm × 75 cm × 100 cm",
    imagen: "Kit de imágenes/Butaca Mendoza.png",
    destacado: true,
  },
  {
    id: 4,
    nombre: "Mesa Comedor Pampa",
    descripcion: "Mesa de comedor en madera maciza, ideal para reuniones familiares.",
    descripcionCompleta: "La Mesa Comedor Pampa es un ícono de la carpintería argentina. Fabricada íntegramente en madera maciza de quebracho colorado, su superficie de 200 cm permite reunir a toda la familia. Cada pieza es única, con vetas naturales que hacen de esta mesa una obra de arte funcional. Resiste el uso cotidiano con la elegancia de siempre.",
    categoria: "Comedor",
    precio: 210000,
    material: "Madera maciza de quebracho colorado",
    dimensiones: "200 cm × 90 cm × 76 cm",
    imagen: "Kit de imágenes/Mesa Comedor Pampa.png",
    destacado: true,
  },
  {
    id: 5,
    nombre: "Mesa de Centro Araucaria",
    descripcion: "Mesa de centro baja, protagonista del living con superficie generosa.",
    descripcionCompleta: "La Mesa de Centro Araucaria aporta calidez y carácter al living. Su diseño de doble bandeja en madera de araucaria permite almacenar revistas, controles y objetos decorativos. La combinación de madera natural con patas de acero pintado crea un contraste moderno y sofisticado que eleva cualquier espacio.",
    categoria: "Living",
    precio: 54000,
    material: "Madera de araucaria, patas de acero",
    dimensiones: "120 cm × 60 cm × 45 cm",
    imagen: "Kit de imágenes/Mesa de Centro Araucaria.png",
    destacado: false,
  },
  {
    id: 6,
    nombre: "Mesa de Noche Aconcagua",
    descripcion: "Mesa de luz compacta, con cajón y superficie de apoyo al lado de la cama.",
    descripcionCompleta: "La Mesa de Noche Aconcagua es el complemento ideal para cualquier dormitorio. Su diseño compacto con un cajón de corredera suave y una balda inferior optimiza el espacio sin sacrificar el estilo. Fabricada en MDF lacado con bordes de madera maciza, combina modernidad y durabilidad para el descanso cotidiano.",
    categoria: "Dormitorio",
    precio: 38000,
    material: "MDF lacado, bordes de madera maciza",
    dimensiones: "50 cm × 40 cm × 55 cm",
    imagen: "Kit de imágenes/Mesa de Noche Aconcagua.png",
    destacado: false,
  },
  {
    id: 7,
    nombre: "Escritorio Costa",
    descripcion: "Escritorio de trabajo con superficie amplia y líneas limpias.",
    descripcionCompleta: "El Escritorio Costa fue concebido para el trabajador moderno que exige organización y espacio. Su superficie de 160 cm ofrece lugar para monitor, laptop y materiales. Con un cajón lateral con cerradura y un estante inferior, mantiene el escritorio siempre ordenado. Fabricado en melamina de alta densidad con canto grueso de PVC.",
    categoria: "Oficina",
    precio: 78000,
    material: "Melamina de alta densidad, canto de PVC grueso",
    dimensiones: "160 cm × 70 cm × 75 cm",
    imagen: "Kit de imágenes/Escritorio Costa.png",
    destacado: false,
  },
  {
    id: 8,
    nombre: "Silla de Trabajo Belgrano",
    descripcion: "Silla de oficina con asiento tapizado y respaldo ergonómico.",
    descripcionCompleta: "La Silla de Trabajo Belgrano fue diseñada pensando en la salud postural. Su respaldo ergonómico con soporte lumbar ajustable y el asiento de espuma de alta densidad tapizado en tela transpirable hacen de esta silla una aliada para jornadas extendidas. Base de cinco puntas en aluminio con ruedas silenciosas de doble rodamiento.",
    categoria: "Oficina",
    precio: 45000,
    material: "Estructura metálica, tapizado en tela transpirable",
    dimensiones: "60 cm × 60 cm × 95–110 cm (ajustable)",
    imagen: "Kit de imágenes/Silla de Trabajo Belgrano.png",
    destacado: false,
  },
  {
    id: 9,
    nombre: "Sillas Córdoba",
    descripcion: "Sillas de comedor con respaldo de madera, pensadas para uso diario.",
    descripcionCompleta: "Las Sillas Córdoba son el complemento perfecto para cualquier mesa de comedor. Su estructura de madera de pino macizo con respaldo en listones horizontales combina resistencia y estética natural. El asiento tapizado en cuerina lavable facilita la limpieza diaria, ideal para familias. Se ofrecen en sets de 4 unidades.",
    categoria: "Comedor",
    precio: 32000,
    material: "Madera de pino macizo, asiento en cuerina",
    dimensiones: "45 cm × 42 cm × 90 cm (por unidad)",
    imagen: "Kit de imágenes/Sillas Córdoba.png",
    destacado: false,
  },
  {
    id: 10,
    nombre: "Aparador Uspallata",
    descripcion: "Aparador de guardado con puertas y estantes, para living o comedor.",
    descripcionCompleta: "El Aparador Uspallata es la solución de almacenamiento más elegante para el comedor o living. Con tres puertas batientes y estantes internos regulables, ofrece una capacidad de guardado excepcional. La combinación de madera maciza de cedro con herrajes de bronce envejecido le da un carácter atemporal que mejora con los años.",
    categoria: "Comedor",
    precio: 145000,
    material: "Madera maciza de cedro, herrajes de bronce envejecido",
    dimensiones: "180 cm × 45 cm × 90 cm",
    imagen: "Kit de imágenes/Aparador Uspallata.png",
    destacado: false,
  },
  {
    id: 11,
    nombre: "Biblioteca Recoleta",
    descripcion: "Biblioteca de estantes abiertos para libros, objetos y vajilla.",
    descripcionCompleta: "La Biblioteca Recoleta es más que un mueble de almacenamiento: es un elemento decorativo que transforma cualquier espacio. Sus seis estantes de madera maciza de algarrobo, con distintas alturas, permiten organizar libros, objetos de arte, plantas y vajilla con criterio estético. El acabado en aceite de tung protege la madera naturalmente.",
    categoria: "Living",
    precio: 118000,
    material: "Madera maciza de algarrobo, acabado en aceite de tung",
    dimensiones: "100 cm × 35 cm × 200 cm",
    imagen: "Kit de imágenes/Biblioteca Recoleta.png",
    destacado: false,
  },
];
